#! /usr/bin/zsh

source ${0:a:h}/../.env

res_hdrs_file=/tmp/curl-headers.dat
res_body_file=/tmp/curl-body.dat

pretty_print_json=(python3 -m json.tool)

function post_request {
	url=http://$APP_HOST:$APP_PORT$1
	data=$2

	if [[ -n $3 ]] ; then
		token_header="Bearer $3"
	fi

	curl -s -X POST \
		-D $res_hdrs_file \
		-H "Authorization: $token_header" \
		-H "Content-Type: application/json" \
		-d "$data" \
		$url >! $res_body_file

	post_body=$(<$res_body_file)
	post_code=`head -n1 $res_hdrs_file`
}

function get_request {
	url=http://$APP_HOST:$APP_PORT$1

	if [[ -n $2 ]] ; then
		token_header="Bearer $2"
	fi

	curl -s -X GET \
		-D $res_hdrs_file \
		-H "Authorization: $token_header" \
		$url | $pretty_print_json[@] 1> $res_body_file

	get_body=$(<$res_body_file)
	get_code=`head -n1 $res_hdrs_file`
}
